# ローカル用
# version: '3'
# services:
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#     ports:
#       - '3306:3306'
#     networks:
#       - rails_api_practice_network

#   app:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/app
#       - public-data:/app/public
#       - tmp-data:/app/tmp
#       - log-data:/app/log
#     ports:
#       - 3000:3000
#     networks:
#       - rails_api_practice_network
#     depends_on:
#       - db
#     tty: true
#     stdin_open: true

# volumes:
#   public-data:
#   tmp-data:
#   log-data:

# networks:
#   rails_api_practice_network:
#     external: true

# デプロイ用
version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - rails_api_practice_network

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - rails_api_practice_network
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    build: ./nginx_docker
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - rails_api_practice_network

volumes:
  public-data:
  tmp-data:
  log-data:

networks:
  rails_api_practice_network:
    external: true

